# Basics of Numpy

In [2]:
L = list(range(10))
print(L)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
L1 = tuple(range(10))
print(L1)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [4]:
a = type(L)
print(a)

<class 'list'>


In [5]:
b = type(L[0])
print(b)

<class 'int'>


In [6]:
# conversion from List to string - by using loop

c = [str(i) for i in L]
print(c)


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [7]:
import array
A = list(range(10))
B = array.array('i' , A)
print(B)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
# Starting Numpy from here before was basics of list

import numpy as np

In [9]:
D = list(range(10))
np.array(D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.array([1, 2,3 ,4,5,6])


array([1, 2, 3, 4, 5, 6])

In [11]:
np.array([1,1.2,4,5,6,7])

array([1. , 1.2, 4. , 5. , 6. , 7. ])

In [12]:
np.array([1,1.2,4,5,6,"7"])

array(['1', '1.2', '4', '5', '6', '7'], dtype='<U32')

In [13]:
np.array([1,2,3,4] , dtype = "float32")


array([1., 2., 3., 4.], dtype=float32)

In [14]:
#Nested list - list k andr list - multi-dimensional list

np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [15]:
# creating array from scrach

np.zeros(10,dtype = int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((3,3) , dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.ones((3,2) ,dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [40]:
np.full((3,3),18)

array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

In [50]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [52]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [60]:
#Method to generate random number in numpy
np.random.random((3,4))

array([[0.43898829, 0.2512463 , 0.16772459, 0.53833241],
       [0.21800208, 0.91022029, 0.89870776, 0.21661712],
       [0.99802728, 0.37110974, 0.24320313, 0.0974748 ]])

In [64]:
np.random.normal(1,2 ,(3,3))

array([[ 3.69594062,  2.69434956,  2.1389486 ],
       [ 2.16473508,  2.4261269 , -0.72974132],
       [ 3.2862991 ,  0.23913802,  1.63813617]])

In [66]:
np.random.randint(0,10)

3

# Learning NumPy again !!  (8/05/2025)


In [11]:
import numpy as np
myarr = np.array([[3,6,67,8]])
myarr
myarr[0,0]

np.int64(3)

In [13]:
myarr[0,1]

np.int64(6)

In [15]:
myarr.shape

(1, 4)

In [17]:
myarr.dtype

dtype('int64')

In [19]:
myarr[0,2] = 34
myarr

array([[ 3,  6, 34,  8]])

In [ ]:
# Array creation : Conversion from other python structure like (list, tuples)

In [23]:
listarray = np.array([[1,2,3], [5,7,8], [9,2,5]])

In [25]:
listarray

array([[1, 2, 3],
       [5, 7, 8],
       [9, 2, 5]])

In [27]:
listarray.dtype

dtype('int64')

In [29]:
listarray.shape

(3, 3)

In [31]:
listarray.size

9

In [33]:
dicarray = np.array({3,6,8})

In [35]:
dicarray

array({8, 3, 6}, dtype=object)

In [ ]:
# Array creation : Conversion from 

In [37]:
zeros = np.zeros((2,3))

In [39]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
zeros.dtype

dtype('float64')

In [43]:
zeros.size

6

In [45]:
rng = np.arange(15)

In [47]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
lspace = np.linspace(1,9,3)

In [51]:
lspace

array([1., 5., 9.])

In [53]:
emp = np.empty((4,6))

In [55]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69119873e-306, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [7.56593017e-307, 1.24610587e-306, 6.23059726e-307,
        8.90104239e-307, 8.90094053e-307, 1.78019626e-306],
       [8.34445562e-308, 9.45699680e-308, 1.11261774e-306,
        1.29060871e-306, 8.34424766e-308, 2.12203497e-312]])

In [57]:
emp_like = np.empty_like(lspace)

In [59]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [65]:
ide = np.identity(10)   # gives identity matrix of desired length

In [71]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
arr = np.arange(99)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [82]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [86]:
arr.ravel()   #becomes 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [88]:
arr.shape

(99,)

In [90]:
# NumPy Axis

In [92]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [94]:
ar = np.array(x)

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
ar.sum(axis=0)

array([12,  8,  9])

In [100]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [104]:
ar.T  # array ko transpose krta h 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [106]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [108]:
ar.ndim

2

In [110]:
ar.size

9

In [112]:
ar.nbytes

72

In [114]:
one = np.array([1,3,4,76,9])

In [116]:
one.argmax()

np.int64(3)

In [118]:
one.argmin()

np.int64(0)

In [122]:
one.argsort()   # gives the index of sorted array

array([0, 1, 2, 4, 3])

In [124]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [126]:
ar.argmin()

np.int64(8)

In [128]:
ar.argmax()

np.int64(6)

In [130]:
ar.argmax(axis=0)

array([2, 1, 1])

In [132]:
ar.argmax(axis=1)

array([2, 2, 0])

In [134]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [138]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [140]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [142]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [144]:
ar2 = np.array([[1,2,1], [4,0,6], [8,1,5]])

In [146]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  5]])

In [148]:
[65, 34] + [78,90]

[65, 34, 78, 90]

In [150]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [155]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 2.23606798]])

In [157]:
ar.sum()

np.int64(29)

In [159]:
ar.max()

np.int64(7)

In [161]:
ar.min()

np.int64(0)

In [163]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [165]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [170]:
np.count_nonzero(ar)

8

In [173]:
import sys

In [175]:
py_ar = [2,5,7,9]

In [177]:
np_ar = np.array(py_ar)